### ISSUE TITLE
Python triple quoted comments not recognized

### ISSUE THREAD

**Issue by FrancescoGd** [tokyo-night/tokyo-night-vscode-theme#89]
Hi, first of all let me tell that i **really love** this beautiful theme, so thank you!
Sadly I had to switch back to using Dracula though because it mismatches Python's multiline comments inside triple quotes for strings (see attached images) and it's a bit confusing.
Any hints?
VSCode version: 1.89.1
Theme version: 1.0.6

![python comment with Tokyo Night](https://github.com/enkia/tokyo-night-vscode-theme/assets/32357315/700b69ee-6ae6-4e0b-b7e2-349bad8fc4c2)

![python comment with Dracula](https://github.com/enkia/tokyo-night-vscode-theme/assets/32357315/a10b7f89-59a8-4576-9762-00cfadf9fde7)

**Comment by FrancescoGd** [comment]
Replying to myself, I see that other themes have these lines, don't know if it's relevant:

```
- name: Docstrings
  scope:
  - string.quoted.docstring.multi
  - string.quoted.docstring.multi.python punctuation.definition.string.begin
  - string.quoted.docstring.multi.python punctuation.definition.string.end
  - string.quoted.docstring.multi.python constant.character.escape
  settings:
    foreground: *COMMENT
```

**Comment by enkia** [comment]
This has been fixed. Let me know if it works for you, @FrancescoGd?

**Comment by FrancescoGd** [comment]
@enkia updated and reactivated, it now works like a charm, thank you so much!🙂

**Comment by zydou** [comment]
@enkia Hello, I still have the problem with theme version `v1.0.8`. I have to switch back to `v1.0.6` to make the multiline comments inside triple quotes to be highlighted.

This is my vscode environment:
```
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-97-generic
```

Note: I have to pin the vscode version to `1.85.2` because this is [the last version which supports Ubuntu 18.04](https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions).

**Comment by enkia** [comment]
@zydou 

Could you put your cursor in one of those comments, open command palette, search _Inspect Editor Tokens and Scopes_ and copy and paste what you see there?

**Comment by zydou** [comment]
Theme version `v1.0.6`:

```
········Args:13 chars
language	python
standard token type	String
foreground	#9ECE6A
background	#1A1B26
contrast ratio	9.36
textmate scopes	string.quoted.docstring.multi.python
source.python
foreground	string
{ "foreground": "#9ECE6A", "fontStyle": "" }
```

Theme version `v1.0.8`:
```
········Args:13 chars
language	python
standard token type	String
foreground	#51597D
background	#1A1B26
contrast ratio	2.50
font style	italic
textmate scopes	string.quoted.docstring.multi.python
source.python
foreground	string.quoted.docstring.multi
{ "foreground": "#51597D" }
```

**Comment by enkia** [comment]
Hey @zydou, looks like you preferred the version that didn't scope these python comments. I prefer to keep it as is. 

Add this to your settings.json to go back to the way they were:

```
"editor.tokenColorCustomizations": {
    "[Tokyo Night Storm]": {
        "textMateRules": [
        {
            "scope": [
                "punctuation.definition.string.begin.python",
                "punctuation.definition.string.end.python",
            ],
            "settings": {
                "foreground": "#89DDFF"
            }
        },
        {
            "scope": "string.quoted.docstring.multi.python",
            "settings": {
                "foreground": "#9ECE6A"
            }
        },
        ]
    }
} 
```

**Comment by zydou** [comment]
> Hey @zydou, looks like you preferred the version that didn't scope these python comments. I prefer to keep it as is.
> 
> Add this to your settings.json to go back to the way they were:
> 
> ```
> "editor.tokenColorCustomizations": {
>     "[Tokyo Night Storm]": {
>         "textMateRules": [
>         {
>             "scope": [
>                 "punctuation.definition.string.begin.python",
>                 "punctuation.definition.string.end.python",
>             ],
>             "settings": {
>                 "foreground": "#89DDFF"
>             }
>         },
>         {
>             "scope": "string.quoted.docstring.multi.python",
>             "settings": {
>                 "foreground": "#9ECE6A"
>             }
>         },
>         ]
>     }
> } 
> ```

Thanks, this works for me!

**Comment by Goldensteev** [comment]
Hey @enkia it seems there is still an issue :

![Screenshot 2024-07-16 at 14 58 15](https://github.com/user-attachments/assets/605cc4c0-bde8-481a-909a-71ce50014dfe)

i have tried the above fix but no luck. Reverting back to 1.0.6 fixes it.

in case you ask the same as above :
1.0.6
```
Controller·for·handl…·user·notifications.41 chars
language	python
standard token type	String
foreground	#9ECE6A
background	#1A1B26
contrast ratio	9.36
textmate scopes	string.quoted.docstring.multi.python
source.python
foreground	string
{ "foreground": "#9ECE6A", "fontStyle": "" }
```

1.0.9
![Screenshot 2024-07-16 at 15 03 24](https://github.com/user-attachments/assets/3afc3fbd-a58e-4326-bee0-cffcfb572754)

**Comment by zydou** [comment]
@Goldensteev hi, have you restarted the vscode? I don't have the problem after adjusting the `settings.json`

![image](https://github.com/user-attachments/assets/ae7572de-d38f-494e-8e37-6d4809011db5)

**Comment by Goldensteev** [comment]
@zdyou you made me doubt but yeah just check and it does not work.

**Comment by zydou** [comment]
@Goldensteev Hi, do you select the correct theme name corresponding with the `settings.json`? For example:

```json
"editor.tokenColorCustomizations": {
    "[Tokyo Night Storm]": {  // You should select theme name: "Tokyo Night Storm"
        ...
    }
}
```

BTW, the following is my current `Inspect Editor Tokens and Scopes` results:
![image](https://github.com/user-attachments/assets/979a1d08-bc3b-476e-980d-3ac037233abf)

**Comment by Goldensteev** [comment]
@zydou ahh yes indeed i forgot i was using Tokyo Night and not storm! working now thanks
